/**
 * Shared formatting helpers for the Forge report renderers.
 *
 * Pure + deterministic: same input always yields the same string. Locale-free
 * (no Intl), timezone-free: timestamps are printed exactly as recorded
 * (ISO-8601 strings compare correctly lexicographically when produced by the
 * same adapter). Missing values render as "-" — never fabricated.
 */
import type { AgentStats, Insight, RunReport, RunTotals } from '../core/model.js';

// ---------------------------------------------------------------------------
// Fixed strings shared by all surfaces ("verbatim-ish" footer disclaimers)
// ---------------------------------------------------------------------------

export const REPORT_TITLE = 'FORGE RUN REPORT';
export const DISCLAIMER_COST =
  'Costs are ESTIMATES from built-in public list prices - override via .forge/prices.json.';
export const DISCLAIMER_FACTS =
  'Facts come from recorded events; suggestions are rule-based inferences, not measurements.';
export const GENERATED_BY = 'Generated by Forge';
export const NO_FINDINGS = 'No findings met evidence thresholds.';

// ---------------------------------------------------------------------------
// Numbers
// ---------------------------------------------------------------------------

/**
 * 3_600_000 -> "1h 00m", 3_420_000 -> "57m 00s", 65_000 -> "1m 05s",
 * 2_400 -> "2.4s", 850 -> "850ms", undefined -> "-"
 */
export function humanizeDuration(ms?: number | null): string {
  if (ms === undefined || ms === null || !Number.isFinite(ms) || ms < 0) return '-';
  if (ms < 1000) return `${Math.round(ms)}ms`;
  const totalSec = Math.round(ms / 1000);
  if (totalSec < 60) return `${(ms / 1000).toFixed(1)}s`;
  const minutes = Math.floor(totalSec / 60);
  const sec = totalSec % 60;
  if (totalSec < 3600) return `${minutes}m ${String(sec).padStart(2, '0')}s`;
  const hours = Math.floor(minutes / 60);
  return `${hours}h ${String(minutes % 60).padStart(2, '0')}m`;
}

/** 2_800_000 -> "2.8M", 384_200 -> "384.2k", 912 -> "912", undefined -> "-" */
export function humanizeTokens(n?: number | null): string {
  if (n === undefined || n === null || !Number.isFinite(n)) return '-';
  const sign = n < 0 ? '-' : '';
  const v = Math.abs(n);
  if (v < 1000) return sign + String(Math.round(v));
  const tiers: Array<[number, string]> = [
    [1e9, 'G'],
    [1e6, 'M'],
    [1e3, 'k'],
  ];
  for (const [div, suffix] of tiers) {
    if (v >= div) {
      let s = (v / div).toFixed(1);
      if (s.endsWith('.0')) s = s.slice(0, -2);
      return sign + s + suffix;
    }
  }
  return sign + String(Math.round(v));
}

/** 18.42 -> "$18.42", 0.0023 -> "$0.0023", undefined -> "-" */
export function formatUsd(v?: number | null): string {
  if (v === undefined || v === null || !Number.isFinite(v)) return '-';
  const sign = v < 0 ? '-' : '';
  const a = Math.abs(v);
  if (a === 0) return `${sign}$0.00`; // zero-cost is a known value, not a missing one
  if (a >= 0.01) return `${sign}$${groupThousands(a.toFixed(2))}`;
  // Sub-cent values keep two significant digits without trailing zeros.
  return `${sign}$${trimZeros(a.toPrecision(2))}`;
}

function groupThousands(s: string): string {
  const dot = s.indexOf('.');
  const intPart = dot === -1 ? s : s.slice(0, dot);
  const fracPart = dot === -1 ? '' : s.slice(dot);
  const grouped = intPart.replace(/\B(?=(\d{3})+(?!\d))/g, ',');
  return grouped + fracPart;
}

function trimZeros(s: string): string {
  if (!s.includes('.')) return s;
  return s.replace(/0+$/, '').replace(/\.$/, '');
}

/** Integer or "-". */
export function num(n?: number | null): string {
  if (n === undefined || n === null || !Number.isFinite(n)) return '-';
  return String(n);
}

/** "43%" — share of `part` in `total`, clamped to [0, 100]. total <= 0 -> "0%". */
export function pct(part: number, total: number, decimals = 0): string {
  return `${pctNum(part, total, decimals)}%`;
}

/** Numeric share (no "%" suffix) for CSS widths; clamped, NaN-safe. */
export function pctNum(part: number, total: number, decimals = 1): number {
  if (!Number.isFinite(part) || !Number.isFinite(total) || total <= 0) return 0;
  const p = Math.min(100, Math.max(0, (part / total) * 100));
  const factor = 10 ** decimals;
  return Math.round(p * factor) / factor;
}

// ---------------------------------------------------------------------------
// Text
// ---------------------------------------------------------------------------

const HTML_ESCAPES: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};

/** Attribute-safe HTML escaping: & < > " ' — mandatory for ALL dynamic strings. */
export function escapeHtml(s: string): string {
  return String(s).replace(/[&<>"']/g, (ch) => HTML_ESCAPES[ch] ?? ch);
}

/** Append "..." when longer than `max` (truncate raw text BEFORE escaping). */
export function truncate(s: string, max: number): string {
  const str = String(s);
  if (max <= 0) return '';
  if (str.length <= max) return str;
  const ell = '...';
  if (max <= ell.length) return str.slice(0, max);
  return str.slice(0, max - ell.length).trimEnd() + ell;
}

/** Collapse all whitespace runs to single spaces. */
export function oneLine(s: string): string {
  return String(s).replace(/\s+/g, ' ').trim();
}

/** Map every character outside printable ASCII (32-126) to '?'. */
export function ascii(s: string): string {
  return String(s).replace(/[^\x20-\x7E]/g, '?');
}

/** Sanitize arbitrary external text for a single-line ASCII terminal cell. */
export function cell(s: unknown): string {
  return ascii(oneLine(s === undefined || s === null ? '' : String(s)));
}

/** Word-wrap to at most `width` columns (words longer than the line are cut). */
export function wrapWords(text: string, width: number): string[] {
  if (width < 1) width = 1;
  const words = oneLine(text).split(' ').filter(Boolean);
  const lines: string[] = [];
  let cur = '';
  for (const rawWord of words) {
    const word = rawWord.length > width ? truncate(rawWord, width) : rawWord;
    if (!cur) cur = word;
    else if (cur.length + 1 + word.length <= width) cur += ` ${word}`;
    else {
      lines.push(cur);
      cur = word;
    }
  }
  lines.push(cur);
  return lines;
}

// ---------------------------------------------------------------------------
// Report-derived shared views
// ---------------------------------------------------------------------------

export interface OrderedAgent {
  agent: AgentStats;
  depth: number;
}

/**
 * Depth-first swarm-tree order: parents immediately followed by their
 * children. Roots and sibling groups sort by display name then id, so the
 * order is deterministic for any input array order. Cycle-safe.
 */
export function orderAgents(agents: AgentStats[]): OrderedAgent[] {
  const byId = new Set(agents.map((a) => a.agentId));
  const childrenOf = new Map<string, AgentStats[]>();
  const roots: AgentStats[] = [];
  for (const a of agents) {
    if (a.parentAgentId && byId.has(a.parentAgentId)) {
      const list = childrenOf.get(a.parentAgentId) ?? [];
      list.push(a);
      childrenOf.set(a.parentAgentId, list);
    } else {
      roots.push(a);
    }
  }
  const byName = (x: AgentStats, y: AgentStats): number =>
    displayName(x).localeCompare(displayName(y)) || x.agentId.localeCompare(y.agentId);
  const seen = new Set<string>();
  const out: OrderedAgent[] = [];
  const visit = (a: AgentStats, depth: number): void => {
    if (seen.has(a.agentId)) return;
    seen.add(a.agentId);
    out.push({ agent: a, depth });
    for (const child of (childrenOf.get(a.agentId) ?? []).slice().sort(byName)) {
      visit(child, depth + 1);
    }
  };
  for (const root of roots.slice().sort(byName)) visit(root, 0);
  return out;
}

export function displayName(a: AgentStats): string {
  return a.name && a.name.trim() !== '' ? a.name.trim() : a.agentId;
}

/** Model ids attributed to an agent, most-used first. */
export function modelsUsed(models: Record<string, number>): string {
  return Object.entries(models)
    .filter(([, tokens]) => Number.isFinite(tokens))
    .sort((x, y) => y[1] - x[1] || x[0].localeCompare(y[0]))
    .map(([id]) => id)
    .join(', ');
}

/**
 * Visible caveat for the estimated-cost figure, or null when the estimate
 * covers everything. RunTotals carries no per-record counter, so the notice
 * speaks of "some records" instead of a fabricated N.
 */
export function costNotice(totals: RunTotals): string | null {
  if (totals.costUsd !== undefined) {
    return totals.costKnown
      ? null
      : 'Pricing was unknown for some usage records; the estimate covers known-priced models only.';
  }
  return totals.costKnown
    ? 'No token usage in this run matched the pricing table.'
    : 'Pricing was unknown for some usage records; no total cost estimate is possible.';
}

/**
 * Activity window (earliest task start -> latest task end, falling back to
 * meta.createdAt). Purely string-based: no clock reads, no timezone math.
 */
export function runWindow(r: RunReport): { start: string; end: string } {
  let start: string | undefined;
  let end: string | undefined;
  for (const t of r.tasks) {
    if (t.startedAt && (start === undefined || t.startedAt < start)) start = t.startedAt;
    const stop = t.endedAt ?? t.startedAt;
    if (stop && (end === undefined || stop > end)) end = stop;
  }
  return { start: start ?? r.meta.createdAt, end: end ?? r.meta.createdAt };
}

/** Insights sorted warn-first, original order preserved within a severity. */
export function sortedInsights(r: RunReport): Insight[] {
  const rank: Record<Insight['severity'], number> = { warn: 0, info: 1 };
  return r.insights
    .map((ins, i) => ({ ins, i }))
    .sort((a, b) => rank[a.ins.severity] - rank[b.ins.severity] || a.i - b.i)
    .map((x) => x.ins);
}
